// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cracker} from '../models';
import {context} from '../models';

export function CancelCrack():Promise<void>;

export function CrackAirDrop(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:number):Promise<cracker.CrackResult>;

export function CrackWXUin(arg1:Array<string>):Promise<cracker.CrackResult>;

export function GetState():Promise<string>;

export function InitCtx(arg1:context.Context):Promise<void>;
