// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCrack() {
  return window['go']['cracker']['ForensicsCracker']['CancelCrack']();
}

export function CrackAirDrop(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['cracker']['ForensicsCracker']['CrackAirDrop'](arg1, arg2, arg3, arg4, arg5);
}

export function CrackWXUin(arg1) {
  return window['go']['cracker']['ForensicsCracker']['CrackWXUin'](arg1);
}

export function GetState() {
  return window['go']['cracker']['ForensicsCracker']['GetState']();
}

export function InitCtx(arg1) {
  return window['go']['cracker']['ForensicsCracker']['InitCtx'](arg1);
}
