// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {reader} from '../models';

export function InitCtx(arg1:context.Context):Promise<void>;

export function ReadLevelDB(arg1:string):Promise<reader.ReadMapResult>;

export function ReadMMKV(arg1:string,arg2:string):Promise<reader.ReadMapResult>;
