// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitCtx(arg1) {
  return window['go']['reader']['FileReader']['InitCtx'](arg1);
}

export function ReadLevelDB(arg1) {
  return window['go']['reader']['FileReader']['ReadLevelDB'](arg1);
}

export function ReadMMKV(arg1, arg2) {
  return window['go']['reader']['FileReader']['ReadMMKV'](arg1, arg2);
}
