// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {extractor} from '../models';
import {context} from '../models';

export function ExtractDbeaver(arg1:string):Promise<extractor.ExtractMapResult>;

export function ExtractFinalShell(arg1:string):Promise<extractor.ExtractMapResult>;

export function ExtractHawk2(arg1:string,arg2:string):Promise<extractor.ExtractMapResult>;

export function ExtractMetaMask(arg1:string):Promise<extractor.ExtractMapResult>;

export function ExtractMobaXterm(arg1:string,arg2:string):Promise<extractor.ExtractMapResult>;

export function ExtractNavicat(arg1:string):Promise<extractor.ExtractMapResult>;

export function ExtractXShell(arg1:string,arg2:string):Promise<extractor.ExtractMapResult>;

export function InitCtx(arg1:context.Context):Promise<void>;
