// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractDbeaver(arg1) {
  return window['go']['extractor']['InfoExtractor']['ExtractDbeaver'](arg1);
}

export function ExtractFinalShell(arg1) {
  return window['go']['extractor']['InfoExtractor']['ExtractFinalShell'](arg1);
}

export function ExtractHawk2(arg1, arg2) {
  return window['go']['extractor']['InfoExtractor']['ExtractHawk2'](arg1, arg2);
}

export function ExtractMetaMask(arg1) {
  return window['go']['extractor']['InfoExtractor']['ExtractMetaMask'](arg1);
}

export function ExtractMobaXterm(arg1, arg2) {
  return window['go']['extractor']['InfoExtractor']['ExtractMobaXterm'](arg1, arg2);
}

export function ExtractNavicat(arg1) {
  return window['go']['extractor']['InfoExtractor']['ExtractNavicat'](arg1);
}

export function ExtractXShell(arg1, arg2) {
  return window['go']['extractor']['InfoExtractor']['ExtractXShell'](arg1, arg2);
}

export function InitCtx(arg1) {
  return window['go']['extractor']['InfoExtractor']['InitCtx'](arg1);
}
