// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {context} from '../models';

export function DecryptAMapDB(arg1:string):Promise<database.DecryptResult>;

export function DecryptDingTalkDB(arg1:string,arg2:string):Promise<database.DecryptResult>;

export function DecryptEnMicroMsg(arg1:string,arg2:string):Promise<database.DecryptResult>;

export function DecryptFTSIndexDB(arg1:string,arg2:string):Promise<database.DecryptResult>;

export function DecryptNtqqDB(arg1:string,arg2:string):Promise<database.DecryptResult>;

export function DecryptSQLCipher3DB(arg1:string,arg2:string):Promise<database.DecryptResult>;

export function DecryptSQLCipher4DB(arg1:string,arg2:string):Promise<database.DecryptResult>;

export function DecryptSystemDataSQLite(arg1:string,arg2:string):Promise<database.DecryptResult>;

export function DecryptWCDB(arg1:string,arg2:string):Promise<database.DecryptResult>;

export function InitCtx(arg1:context.Context):Promise<void>;
