// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptAMapDB(arg1) {
  return window['go']['database']['DecryptDatabase']['DecryptAMapDB'](arg1);
}

export function DecryptDingTalkDB(arg1, arg2) {
  return window['go']['database']['DecryptDatabase']['DecryptDingTalkDB'](arg1, arg2);
}

export function DecryptEnMicroMsg(arg1, arg2) {
  return window['go']['database']['DecryptDatabase']['DecryptEnMicroMsg'](arg1, arg2);
}

export function DecryptFTSIndexDB(arg1, arg2) {
  return window['go']['database']['DecryptDatabase']['DecryptFTSIndexDB'](arg1, arg2);
}

export function DecryptNtqqDB(arg1, arg2) {
  return window['go']['database']['DecryptDatabase']['DecryptNtqqDB'](arg1, arg2);
}

export function DecryptSQLCipher3DB(arg1, arg2) {
  return window['go']['database']['DecryptDatabase']['DecryptSQLCipher3DB'](arg1, arg2);
}

export function DecryptSQLCipher4DB(arg1, arg2) {
  return window['go']['database']['DecryptDatabase']['DecryptSQLCipher4DB'](arg1, arg2);
}

export function DecryptSystemDataSQLite(arg1, arg2) {
  return window['go']['database']['DecryptDatabase']['DecryptSystemDataSQLite'](arg1, arg2);
}

export function DecryptWCDB(arg1, arg2) {
  return window['go']['database']['DecryptDatabase']['DecryptWCDB'](arg1, arg2);
}

export function InitCtx(arg1) {
  return window['go']['database']['DecryptDatabase']['InitCtx'](arg1);
}
