// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {winreg} from '../models';
import {context} from '../models';

export function AnalyzeWinReg(arg1:string):Promise<winreg.RegResult>;

export function InitCtx(arg1:context.Context):Promise<void>;
