// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeWinReg(arg1) {
  return window['go']['winreg']['Reg']['AnalyzeWinReg'](arg1);
}

export function InitCtx(arg1) {
  return window['go']['winreg']['Reg']['InitCtx'](arg1);
}
