// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitCtx(arg1) {
  return window['go']['timestamp']['TimeStampParser']['InitCtx'](arg1);
}

export function ParseTimeStamp(arg1, arg2, arg3) {
  return window['go']['timestamp']['TimeStampParser']['ParseTimeStamp'](arg1, arg2, arg3);
}
