// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function InitCtx(arg1:context.Context):Promise<void>;

export function ParseTimeStamp(arg1:string,arg2:string,arg3:string):Promise<string>;
