// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalBatChat(arg1) {
  return window['go']['passwdCalc']['PasswdCalc']['CalBatChat'](arg1);
}

export function CalMostone(arg1) {
  return window['go']['passwdCalc']['PasswdCalc']['CalMostone'](arg1);
}

export function CalTiktok(arg1) {
  return window['go']['passwdCalc']['PasswdCalc']['CalTiktok'](arg1);
}

export function CalWechat(arg1, arg2) {
  return window['go']['passwdCalc']['PasswdCalc']['CalWechat'](arg1, arg2);
}

export function CalWechatIndex(arg1, arg2, arg3) {
  return window['go']['passwdCalc']['PasswdCalc']['CalWechatIndex'](arg1, arg2, arg3);
}

export function CalWildFire(arg1) {
  return window['go']['passwdCalc']['PasswdCalc']['CalWildFire'](arg1);
}

export function InitCtx(arg1) {
  return window['go']['passwdCalc']['PasswdCalc']['InitCtx'](arg1);
}
