// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CalMostone(arg1:string):Promise<Array<string>>;

export function CalTiktok(arg1:string):Promise<Array<string>>;

export function CalWechat(arg1:string,arg2:string):Promise<string>;

export function CalWechatIndex(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CalWildFire(arg1:string):Promise<Array<string>>;

export function InitCtx(arg1:context.Context):Promise<void>;
