// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {ip} from '../models';

export function CheckDB():Promise<void>;

export function CheckUpdate():Promise<boolean>;

export function InitCtx(arg1:context.Context):Promise<void>;

export function LoadDB():Promise<void>;

export function Search(arg1:string):Promise<ip.CZIP>;

export function SearchAll(arg1:Array<string>):Promise<Record<string, ip.CZIP>>;

export function UpdateDB():Promise<void>;
