// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDB() {
  return window['go']['ip']['IP']['CheckDB']();
}

export function CheckUpdate() {
  return window['go']['ip']['IP']['CheckUpdate']();
}

export function InitCtx(arg1) {
  return window['go']['ip']['IP']['InitCtx'](arg1);
}

export function LoadDB() {
  return window['go']['ip']['IP']['LoadDB']();
}

export function Search(arg1) {
  return window['go']['ip']['IP']['Search'](arg1);
}

export function SearchAll(arg1) {
  return window['go']['ip']['IP']['SearchAll'](arg1);
}

export function UpdateDB() {
  return window['go']['ip']['IP']['UpdateDB']();
}
